"""Add related_ids column to Shoes

Revision ID: 0b173a209169
Revises: bc11bfbf4ad1
Create Date: 2025-06-01 16:45:11.065651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b173a209169'
down_revision = 'bc11bfbf4ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_ids', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('related_ids')

    # ### end Alembic commands ###
