"""Add featured column to Shoes

Revision ID: 12437fce7ff1
Revises: 3ee42e0241f9
Create Date: 2025-05-30 22:54:18.273327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12437fce7ff1'
down_revision = '3ee42e0241f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('Shoes', schema=None) as batch_op:
    batch_op.alter_column('main_image',
               type_=sa.Text(),
               existing_type=sa.String(length=300),
               existing_nullable=True)
    batch_op.alter_column('gallery',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.alter_column('gallery',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('main_image',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
