"""Add date_added column to Shoes for new arrivals

Revision ID: 6529ff0fec19
Revises: a2693b4cc054
Create Date: 2025-06-19 00:02:17.633186

"""
from alembic import op
from datetime import date
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6529ff0fec19'
down_revision = 'a2693b4cc054'
branch_labels = None
depends_on = None


def upgrade():
    # Set a default value for existing rows (e.g., today)
    op.add_column('Shoes', sa.Column('date_added', sa.Date(), nullable=False, server_default=sa.text(f"'{date.today().isoformat()}'")))
    # Remove the server default if you want after the column is added:
    op.alter_column('Shoes', 'date_added', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
