"""Add sale fields to Shoes

Revision ID: a2693b4cc054
Revises: e0a500d90e71
Create Date: 2025-06-18 16:16:26.013711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2693b4cc054'
down_revision = 'e0a500d90e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sale')
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('sale_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sale_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('sale_end_date')
        batch_op.drop_column('sale_start_date')
        batch_op.drop_column('sale_price')

    op.create_table('Sale',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sizes', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('style', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Sale_pkey'))
    )
    # ### end Alembic commands ###
