"""add featured column to shoes

Revision ID: bc11bfbf4ad1
Revises: 12437fce7ff1
Create Date: 2025-05-31 00:00:47.963682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc11bfbf4ad1'
down_revision = '12437fce7ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
