"""Add shipping_method and shipping_cost to Order

Revision ID: fe31ec8beb48
Revises: bb9de28f060d
Create Date: 2025-06-13 00:01:03.020927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe31ec8beb48'
down_revision = 'bb9de28f060d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
      batch_op.add_column(sa.Column('shipping_method', sa.String(length=50), nullable=False, server_default='standard'))
      batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=False, server_default='0'))
   
     # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('shipping_method')

    # ### end Alembic commands ###
